name: build

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Install Computo extension for Quarto
        run: |
          quarto add --no-prompt computorg/computo-quarto-extension

      - name: Trigger external workflow
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_DISPATCH_TOKEN }}
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: 'Qufst',
              repo: 'projet-personnel-m-t-o',
              event_type: 'custom-event',
              client_payload: {
                ref: 'main', // Branch you want to trigger the workflow on
                additional_parameter: 'value' // Additional parameters if needed
              }
            })
