name: build

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Install Computo extension for Quarto
        run: |
          quarto add --no-prompt computorg/computo-quarto-extension

          - name: Trigger external workflow with empty commit
          env:
            GITHUB_TOKEN: ${{ secrets.REPO_DISPATCH_TOKEN }}
          run: |
            git clone https://github.com/Qufst/projet-personnel-m-t-o.git
            cd projet-personnel-m-t-o
            git config --global user.email "your-email@example.com"
            git config --global user.name "Your Name"
            git checkout main
            git commit --allow-empty -m "Trigger workflow from another repo"
            git push origin main