name: Build

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Install Computo extension for Quarto
        run: |
          quarto add --no-prompt computorg/computo-quarto-extension

      - name: Trigger external workflow with empty commit
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_DISPATCH_TOKEN }}
          GITHUB_REPOSITORY_URL: https://x-access-token:${{ secrets.REPO_DISPATCH_TOKEN }}@github.com/Qufst/projet-personnel-m-t-o.git
        run: |
          git clone https://github.com/Qufst/projet-personnel-m-t-o.git
          cd projet-personnel-m-t-o
          git config --global user.email "quentin.festor@etu.umontpellier.fr"
          git config --global user.name "Qufst"
          git checkout main
          git commit --allow-empty -m "Trigger workflow from another repo"
          git remote set-url origin https://github.com/Qufst/projet-personnel-m-t-o.git
          git push $GITHUB_REPOSITORY_URL origin main
