name: Build

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Install Computo extension for Quarto
        run: |
          quarto add --no-prompt computorg/computo-quarto-extension
        env:
          REPO_DISPATCH_TOKEN: ${{ secrets.token }}
        run: |
          git clone https://x-access-token:${{ secrets.token }}@github.com/Qufst/projet-personnel-m-t-o.git
          cd projet-personnel-m-t-o
          git config --global user.email "quentin.festor@etu.umontpellier.fr"
          git config --global user.name "Qufst"
          git checkout main
          git commit --allow-empty -m "Trigger workflow from another repo"
          git push https://x-access-token:${{ secrets.token }}@github.com/Qufst/projet-personnel-m-t-o.git main