name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call_quarto_workflows:
    uses: ./.github/workflows/quarto_workflows.yml
    with:
      config-path: './config/quarto_config.yml'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  call_micromamba_workflows:
    uses: ./.github/workflows/micromamba_workflows.yml
    with:
      config-path: './config/micromamba_config.yml'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  call_build:
    uses: ./.github/workflows/build.yml
    with:
      config-path: './config/build_config.yml'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  custom-event:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    uses: Qufst/projet-personnel-m-t-o/.github/workflows/build.yml@main
    with:
      config-path: 'Qufst/projet-personnel-m-t-o/environment.yml'
    secrets:
      token: ${{ secrets.REPO_DISPATCH_TOKEN }}
