name: render

on:
  workflow_call:
    inputs:
      config-path: './config/quarto_config.yml'
    secrets:
      token:
        required: true
  workflow_dispatch:


jobs:
  quarto:
    runs-on: ubuntu-latest

    steps:
      - name: Render and publish with Quarto
        run: |
          quarto render ./index.qmd